/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4E9eV4Bxvk4
 */
import { CarouselItem, CarouselContent, CarouselPrevious, CarouselNext, Carousel } from "@/components/ui/carousel"

export function Component() {
  return (
    (<Carousel className="w-full max-w-3xl margin-auto">
      <CarouselContent>
        <CarouselItem>
          <div className="flex flex-col items-center p-2">
            <img
              alt="Image"
              className="aspect-video object-cover rounded-lg"
              height={281}
              src="/placeholder.svg"
              width={500} />
            <p className="text-sm font-medium mt-2">A beautiful landscape</p>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="flex flex-col items-center p-2">
            <img
              alt="Image"
              className="aspect-video object-cover rounded-lg"
              height={281}
              src="/placeholder.svg"
              width={500} />
            <p className="text-sm font-medium mt-2">Cute puppies playing</p>
          </div>
        </CarouselItem>
        <CarouselItem>
          <div className="flex flex-col items-center p-2">
            <img
              alt="Image"
              className="aspect-video object-cover rounded-lg"
              height={281}
              src="/placeholder.svg"
              width={500} />
            <p className="text-sm font-medium mt-2">City skyline at night</p>
          </div>
        </CarouselItem>
      </CarouselContent>
      <CarouselPrevious />
      <CarouselNext />
    </Carousel>)
  );
}
